databaseType = "MySql"
id = "d5f12b89-83fe-4bf6-90fc-1f5aaf1b43c0"
name = "vet-clinic"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.db]
url = "jdbc:mysql://localhost:3306"
schemas = [ "vet-clinic" ]
displayName = "vet_clinic"
