spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vet-clinic
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: on
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/vet-clinic
    user: root
    password: root
    baseline-version: 0
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  secret: "dsQFUoEwQnqfaKx65h6D60ISJ2TfC4bkTOgZbSmqBT4="
  expiration: 86400
stripe:
  api_key: "sk_test_51P2srwJriED6n5QK5icHdkX8pr8t8JRmEt8cmukD9qthkmSznbkYppwLXI9QOfA2m4G8HJ73TA0FkDZRGEJGlB4A00cS5u7CyJ"
domain:
  front.end: "http://localhost:5173/account"